### PR TITLE
Merge with edubart

### PR DESCRIPTION
**Pull request by Znote**
Keeping otland/otclient up to date by merging in changes done to edubart/otclient
This is mostly just a test that I expect to fail, just curious about what Travis CI has to say.

### CODE REVIEW

**Comment by Znote** [comment]
Hmm, apparently you cant just willy-nilly resolve conflicts in the build tool and expect things to work out :P

**Comment by Znote** [comment]
ohh, it compiles!
AppVeyor build:
https://ci.appveyor.com/project/Znote/otclient/builds/33624564

**Comment by vfjpl** [comment]
Sooo, anyone sill alive?

**Comment by Znote** [comment]
> Sooo, anyone sill alive?

Yep.
Have you tested this?

**Comment by vfjpl** [comment]
@Znote builds sucesfully and works on gcc 10.1 on linux

**Comment by Znote** [comment]
Merge resolved in another PR: #57

**Pull request closed without merging**
